spring.application.name=scraptrade-backend
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/scraptrade_db
spring.datasource.username=postgres
spring.datasource.password=fuse1234

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cloudinary Configuration
cloudinary.cloud-name=dlv8y3mzb
cloudinary.api-key=978648961841582
cloudinary.api-secret=FvGit5i8J4JJUlgszkcNTSDsPkY

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB